apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: capstone1
data:
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "appdb"
  NODE_ENV: "production"
  API_BASE_URL: "/api"
