apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: capstone1
type: Opaque
stringData:
  DB_USER: "appuser"
  DB_PASSWORD: "Kx9vLp2Rq7zM4t"
  JWT_SECRET: "J8fQw2eR9tYu6iOp1aSd3fGh5jKl7zXc"
